version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./.docker/mongodb:/data/db
    ports:
      - "27017:27017"
    logging:
      options:
        max-size: 10m
        max-file: "3"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: josuebarros1995
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    links:
      - mongo
    depends_on:
      - mongo
